export type GlossaryCategory =
  | 'Foundations'
  | 'IPv4'
  | 'Subnetting'
  | 'IPv6'
  | 'Routing'
  | 'Operations'

export type GlossaryEntry = {
  id: string
  term: string
  aka?: string
  category: GlossaryCategory
  short: string
  long: string
  example?: string
}

/**
 * Every component named anywhere in the course has an entry here. The <Term>
 * component looks entries up by id, so ids are stable, kebab-case, and short.
 */
export const GLOSSARY: GlossaryEntry[] = [
  {
    id: 'bit',
    term: 'Bit',
    category: 'Foundations',
    short: 'A single binary digit — 0 or 1 — and the atom every address is built from.',
    long: 'A bit is one position in a binary number, holding either 0 or 1. Addressing is entirely a game of bits: an IPv4 address is 32 of them, an IPv6 address is 128. Every subnetting question ("how many subnets?", "how many hosts?") reduces to counting how many bits you have left, because n bits express exactly 2^n distinct values.',
    example: '8 bits → 2^8 = 256 distinct values (0–255).',
  },
  {
    id: 'octet',
    term: 'Octet',
    aka: 'byte',
    category: 'IPv4',
    short: 'A group of 8 bits. An IPv4 address is written as four octets separated by dots.',
    long: 'An octet is 8 bits, so it holds a value from 0 to 255. IPv4 splits its 32 bits into four octets purely for human readability — the wire format is one continuous 32-bit field. The dots have no meaning to a router; they are punctuation for people. This matters when a mask lands mid-octet, because the "natural" boundary you see in the text is not a boundary the hardware cares about.',
    example: '192.168.10.37 → octets 192, 168, 10, 37.',
  },
  {
    id: 'dotted-decimal',
    term: 'Dotted decimal',
    aka: 'dotted quad',
    category: 'IPv4',
    short: 'The human-readable IPv4 notation: four decimal numbers 0–255 joined by dots.',
    long: 'Dotted decimal converts each of the four octets to a decimal number. It exists only so people can read and type addresses; conversion to and from binary is where all the actual subnetting work happens.',
    example: '11000000.10101000.00001010.00100101 = 192.168.10.37',
  },
  {
    id: 'hextet',
    term: 'Hextet',
    aka: 'quibble, 16-bit group',
    category: 'IPv6',
    short: 'A group of 16 bits written as four hex digits. An IPv6 address has eight of them.',
    long: 'IPv6 groups its 128 bits into eight 16-bit fields separated by colons, each written as up to four hexadecimal digits. "Hextet" is the common informal name; the RFCs simply say "16-bit group". Each hex digit represents exactly 4 bits (a nibble), which is why IPv6 prefix boundaries on 4-bit multiples are so much easier to read than IPv4 ones.',
    example: '2001:0db8:acad:0010:: → hextets 2001, 0db8, acad, 0010, 0, 0, 0, 0',
  },
  {
    id: 'nibble',
    term: 'Nibble',
    category: 'IPv6',
    short: 'Four bits — one hexadecimal digit.',
    long: 'A nibble is half a byte. In IPv6 it is the practical unit of prefix design: prefixes that land on a nibble boundary (/48, /52, /56, /60, /64) can be read straight off the hex digits, while a /49 or /61 forces you back into binary.',
  },
  {
    id: 'ip-address',
    term: 'IP address',
    category: 'Foundations',
    short: 'A layer-3 identifier for an interface, made of a network part and a host part.',
    long: 'An IP address identifies an interface on a network, not a device — a router with six interfaces has at least six addresses. Every address is really two fields glued together: a network portion shared by everything on the same link, and a host portion unique within it. The mask is what tells you where the split falls.',
  },
  {
    id: 'subnet',
    term: 'Subnet',
    aka: 'subnetwork',
    category: 'Subnetting',
    short: 'A contiguous, power-of-two-sized slice of an IP network that shares one broadcast domain.',
    long: 'A subnet is a block of addresses that all share the same network prefix. Hosts inside it reach each other directly at layer 2; anything outside it has to go through a router. Because the split is done with a bit mask, a subnet is always a power of two in size and always starts on a boundary that is a multiple of that size.',
  },
  {
    id: 'subnet-mask',
    term: 'Subnet mask',
    category: 'Subnetting',
    short: 'A 32-bit value whose 1 bits mark the network portion and 0 bits mark the host portion.',
    long: 'The mask is the second half of an address assignment; an address without one is ambiguous. Its 1 bits are contiguous and left-aligned. A host ANDs its own address with the mask to learn its network address, then ANDs the destination the same way: same result means "deliver locally", different result means "send it to the default gateway".',
    example: '255.255.255.0 = 11111111.11111111.11111111.00000000 = /24',
  },
  {
    id: 'prefix-length',
    term: 'Prefix length',
    aka: 'slash notation',
    category: 'Subnetting',
    short: 'The count of leading 1 bits in the mask, written as /n.',
    long: 'Prefix length is the same information as a subnet mask, written as a count instead of a bit pattern. /24 and 255.255.255.0 are identical. IPv6 uses prefix length exclusively — there is no dotted mask form. The remaining 32 - n (or 128 - n) bits are the host bits.',
  },
  {
    id: 'cidr',
    term: 'CIDR',
    aka: 'Classless Inter-Domain Routing',
    category: 'Subnetting',
    short: 'The addressing scheme that replaced classes, letting a prefix be any length.',
    long: 'CIDR (RFC 4632) removed the fixed A/B/C boundaries and made the prefix length an explicit part of every route and every address assignment. It brought two things the classful internet could not do: variable-length subnet masks inside an organization, and route aggregation between them. Every modern network is classless — classes survive only as vocabulary and as default masks in old CLI shortcuts.',
  },
  {
    id: 'network-address',
    term: 'Network address',
    aka: 'network ID, subnet address',
    category: 'Subnetting',
    short: 'The first address in a subnet — all host bits set to 0. It names the subnet itself.',
    long: 'Setting every host bit to 0 gives the network address. It is not assignable to an interface in IPv4; it is the label routers use in their routing tables. Getting it is a single AND of any address in the block with the mask.',
    example: '192.168.10.37/26 → 192.168.10.0/26',
  },
  {
    id: 'broadcast-address',
    term: 'Broadcast address',
    category: 'IPv4',
    short: 'The last address in an IPv4 subnet — all host bits set to 1. Reaches every host on the link.',
    long: 'A packet sent to the directed broadcast address is delivered to every host in that subnet. Because it is reserved, it costs you one address per subnet — which together with the network address is where "subtract 2" comes from. IPv6 has no broadcast address at all; it uses multicast groups instead.',
    example: '192.168.10.0/26 → broadcast 192.168.10.63',
  },
  {
    id: 'usable-hosts',
    term: 'Usable hosts',
    category: 'Subnetting',
    short: '2^h − 2 addresses in an IPv4 subnet, where h is the number of host bits.',
    long: 'Of the 2^h addresses in a subnet, the first (network) and last (broadcast) are reserved, leaving 2^h − 2 for interfaces. Two exceptions: a /31 gives you 2 usable addresses on point-to-point links (RFC 3021), and a /32 is a single host route. IPv6 does not subtract anything — every address in a /64 except the subnet-router anycast address is assignable.',
  },
  {
    id: 'host-bits',
    term: 'Host bits',
    category: 'Subnetting',
    short: 'The bits to the right of the prefix. They vary within a subnet and count its size.',
    long: 'Host bits are what is left after the prefix. They determine subnet size (2^h addresses) and nothing else. Borrowing a host bit for the network portion halves subnet size and doubles subnet count — the single trade-off at the centre of all subnetting.',
  },
  {
    id: 'borrowed-bits',
    term: 'Borrowed bits',
    category: 'Subnetting',
    short: 'Host bits moved into the network portion to create more, smaller subnets.',
    long: 'When you subnet a block, you take bits from the host side and give them to the network side. Borrow s bits and you get 2^s subnets, each with 2^(h−s) addresses. The borrowed bits are sometimes called the subnet ID field.',
    example: 'Borrow 2 bits from a /24 → four /26s of 64 addresses each.',
  },
  {
    id: 'vlsm',
    term: 'VLSM',
    aka: 'Variable Length Subnet Masking',
    category: 'Subnetting',
    short: 'Using different prefix lengths inside one network so each subnet is sized to its need.',
    long: 'VLSM means subnetting a block unevenly: a /26 for a user VLAN, a /30 for a point-to-point link, a /29 for a server segment. It requires a classless routing protocol (OSPF, EIGRP, IS-IS, BGP) because the mask must travel with each route. Allocating largest-first is what keeps every block aligned and avoids stranded gaps.',
  },
  {
    id: 'summarization',
    term: 'Summarization',
    aka: 'supernetting, aggregation, route summarization',
    category: 'Routing',
    short: 'Advertising many contiguous prefixes as one shorter prefix.',
    long: 'Summarization replaces a set of routes with a single route covering all of them, by keeping only the bits every member shares. It shrinks routing tables, cuts convergence time, and hides link flaps inside the summarized region. It only works when the addresses were assigned contiguously — which is why address plans are designed hierarchically before the first device is configured.',
    example: '10.1.0.0/24 … 10.1.3.0/24 → 10.1.0.0/22',
  },
  {
    id: 'wildcard-mask',
    term: 'Wildcard mask',
    aka: 'inverse mask',
    category: 'Operations',
    short: 'The bitwise inverse of a subnet mask; 0 means "must match", 1 means "ignore".',
    long: 'Wildcard masks appear in ACLs and in OSPF network statements on Cisco IOS. They are simply the subnet mask with every bit flipped, and can express non-contiguous patterns that a subnet mask cannot.',
    example: '/26 → mask 255.255.255.192 → wildcard 0.0.0.63',
  },
  {
    id: 'broadcast-domain',
    term: 'Broadcast domain',
    category: 'Foundations',
    short: 'The set of devices that receive one another’s layer-2 broadcast frames.',
    long: 'A broadcast domain is bounded by routers. Every device in it hears every ARP request, every DHCP discover, and every misbehaving host’s broadcast storm. Subnetting is, operationally, the act of drawing broadcast-domain boundaries: one subnet, one VLAN, one broadcast domain is the standard mapping.',
  },
  {
    id: 'collision-domain',
    term: 'Collision domain',
    category: 'Foundations',
    short: 'A shared-media segment where two transmissions can collide. Switch ports end them.',
    long: 'Collision domains were a hub-era concern; a full-duplex switch port is its own collision domain, so on modern networks they are effectively per-port and no longer a design factor. They are worth knowing only to contrast with broadcast domains, which switches do not break up.',
  },
  {
    id: 'vlan',
    term: 'VLAN',
    aka: 'Virtual LAN',
    category: 'Operations',
    short: 'A layer-2 broadcast domain defined in switch configuration rather than by cabling.',
    long: 'A VLAN partitions one physical switched fabric into several independent layer-2 networks, each tagged with a 802.1Q VLAN ID. In practice a VLAN and an IP subnet are paired one-to-one: the VLAN is the layer-2 boundary, the subnet is the layer-3 addressing that rides on it.',
  },
  {
    id: 'svi',
    term: 'SVI',
    aka: 'Switched Virtual Interface, VLAN interface',
    category: 'Operations',
    short: 'A layer-3 interface on a switch that acts as the default gateway for a VLAN.',
    long: 'An SVI gives a VLAN its routed presence. It holds the gateway address for the subnet mapped to that VLAN, and it is where inter-VLAN routing, ACLs, and DHCP relay are configured.',
  },
  {
    id: 'default-gateway',
    term: 'Default gateway',
    category: 'Foundations',
    short: 'The router address a host sends packets to when the destination is outside its subnet.',
    long: 'After a host ANDs the destination address with its own mask and finds a different network, it hands the packet to its default gateway. The gateway must live inside the host’s own subnet — a mismatched mask that puts the gateway "outside" is one of the most common subnetting faults in production.',
  },
  {
    id: 'arp',
    term: 'ARP',
    aka: 'Address Resolution Protocol',
    category: 'Foundations',
    short: 'Maps an IPv4 address to a MAC address inside one broadcast domain.',
    long: 'A host that wants to talk to an IPv4 address on its own subnet broadcasts an ARP request and caches the reply. ARP is confined to the local subnet, so ARP traffic scales with broadcast-domain size — a direct, measurable cost of building subnets that are too large. IPv6 replaces ARP with Neighbor Discovery over multicast.',
  },
  {
    id: 'nd',
    term: 'Neighbor Discovery',
    aka: 'NDP, ICMPv6 ND',
    category: 'IPv6',
    short: 'IPv6’s replacement for ARP, built on ICMPv6 multicast.',
    long: 'Neighbor Discovery (RFC 4861) handles address resolution, router discovery, prefix advertisement, and duplicate address detection. Because it uses solicited-node multicast rather than broadcast, only the handful of hosts whose addresses share the last 24 bits are interrupted — a quiet but real efficiency gain over ARP.',
  },
  {
    id: 'dhcp',
    term: 'DHCP',
    category: 'Operations',
    short: 'Hands hosts an address, mask, gateway, and DNS servers automatically.',
    long: 'DHCP leases addresses from a pool scoped to one subnet. Because DHCP discovery is a broadcast, a server outside the subnet needs a DHCP relay (ip helper-address) on the gateway interface. Each subnet you create is another scope to define, which is part of why subnets are not free operationally.',
  },
  {
    id: 'slaac',
    term: 'SLAAC',
    aka: 'Stateless Address Autoconfiguration',
    category: 'IPv6',
    short: 'IPv6 hosts build their own address from a router-advertised /64 prefix.',
    long: 'A router sends Router Advertisements containing a prefix; the host appends its own interface identifier and starts using the result after duplicate address detection. SLAAC needs a /64 — the interface identifier is defined as 64 bits — which is why /64 is the universal LAN prefix size in IPv6 regardless of how many hosts are on the link.',
  },
  {
    id: 'eui-64',
    term: 'Modified EUI-64',
    category: 'IPv6',
    short: 'A way to derive a 64-bit interface ID from a 48-bit MAC address.',
    long: 'Split the MAC in half, insert ff:fe in the middle, and flip the universal/local bit (bit 7 of the first byte). The result is a stable interface identifier. Because it exposes the hardware address, most operating systems now default to RFC 8981 temporary addresses or RFC 7217 stable-but-opaque identifiers instead, but EUI-64 is still what you see on router interfaces and in exam questions.',
  },
  {
    id: 'interface-id',
    term: 'Interface identifier',
    category: 'IPv6',
    short: 'The low 64 bits of a typical IPv6 address — the host portion.',
    long: 'In standard IPv6 unicast addressing the last 64 bits identify the interface on the link. They may come from SLAAC, EUI-64, DHCPv6, a privacy extension, or manual configuration. Keeping this field at 64 bits is what makes SLAAC work everywhere.',
  },
  {
    id: 'global-routing-prefix',
    term: 'Global routing prefix',
    category: 'IPv6',
    short: 'The leading bits of an IPv6 address delegated to you by your ISP or RIR — commonly /48.',
    long: 'The global routing prefix is the part of the address the internet routes on and that you do not control. A typical site receives a /48, leaving 16 bits of subnet ID before the 64-bit interface identifier: 65,536 subnets from a single allocation.',
  },
  {
    id: 'subnet-id',
    term: 'Subnet ID',
    category: 'IPv6',
    short: 'The bits between the global routing prefix and the interface identifier.',
    long: 'In a /48 assignment the subnet ID is the 16 bits from /48 to /64. This is the field you design: site, building, floor, function, or VLAN number can each own a nibble of it, which makes addresses readable and summarization straightforward.',
  },
  {
    id: 'gua',
    term: 'Global unicast address',
    aka: 'GUA',
    category: 'IPv6',
    short: 'A publicly routable IPv6 address; everything in 2000::/3.',
    long: 'GUAs are the IPv6 equivalent of public IPv4 addresses, except that every host gets one — there is no address scarcity forcing NAT. Any address beginning with a 2 or 3 hex digit is global unicast.',
  },
  {
    id: 'ula',
    term: 'Unique local address',
    aka: 'ULA',
    category: 'IPv6',
    short: 'Private IPv6 addressing in fc00::/7, in practice fd00::/8 with a random 40-bit global ID.',
    long: 'ULAs fill the RFC 1918 role for IPv6: internal-only addressing that is not routed on the internet. The 40-bit random global ID makes collisions between merging organizations vanishingly unlikely — the failure mode that made everyone’s 10.0.0.0/8 painful. ULAs are typically deployed alongside GUAs, not instead of them.',
  },
  {
    id: 'link-local',
    term: 'Link-local address',
    category: 'IPv6',
    short: 'An fe80::/10 address every IPv6 interface configures automatically; never routed.',
    long: 'Link-local addresses exist on every IPv6-enabled interface and are used for Neighbor Discovery, Router Advertisements, OSPFv3 adjacencies, and BGP next-hops. They are scoped to a single link, so the same address can exist on many interfaces and a zone index (%eth0) is needed to disambiguate.',
  },
  {
    id: 'anycast',
    term: 'Anycast',
    category: 'Routing',
    short: 'One address advertised from many locations; traffic goes to the nearest instance.',
    long: 'Anycast lets several servers share an address, with routing picking the closest. It underpins public DNS resolvers and CDN edges. In IPv6, the all-zeros interface identifier of a subnet is reserved as the subnet-router anycast address.',
  },
  {
    id: 'multicast',
    term: 'Multicast',
    category: 'Routing',
    short: 'One-to-many delivery to hosts that have joined a group address.',
    long: 'Multicast sends a single packet to a group of interested receivers. IPv4 uses 224.0.0.0/4; IPv6 uses ff00::/8 and relies on multicast for functions IPv4 handled with broadcast, which is why IPv6 has no broadcast address.',
  },
  {
    id: 'rfc1918',
    term: 'RFC 1918 space',
    aka: 'private address space',
    category: 'IPv4',
    short: '10.0.0.0/8, 172.16.0.0/12, and 192.168.0.0/16 — private, non-internet-routable IPv4.',
    long: 'These three blocks are reserved for internal use and are dropped by internet routers. Almost every enterprise network is built from them, with NAT translating to public addresses at the edge. The classic operational hazard is overlap: two organizations that both used 10.0.0.0/16 cannot be merged or VPN’d together without renumbering or NAT.',
  },
  {
    id: 'nat',
    term: 'NAT',
    aka: 'Network Address Translation, PAT',
    category: 'Operations',
    short: 'Rewrites addresses (and usually ports) so private hosts can use a shared public address.',
    long: 'NAT was the answer to IPv4 exhaustion: many private hosts behind one public address, distinguished by port. It breaks end-to-end addressing, complicates inbound connections, and its stateful table is a scaling limit. IPv6’s address abundance is meant to remove the need for it entirely.',
  },
  {
    id: 'routing-table',
    term: 'Routing table',
    aka: 'RIB / FIB',
    category: 'Routing',
    short: 'The set of prefixes a router knows and the next hop for each.',
    long: 'Each entry is a prefix plus a next hop. Table size drives memory and convergence time on every router in the path, which is the reason summarization matters at scale: an aggregated design turns thousands of prefixes into dozens.',
  },
  {
    id: 'longest-prefix-match',
    term: 'Longest prefix match',
    category: 'Routing',
    short: 'A router forwards using the most specific matching prefix, regardless of protocol or metric.',
    long: 'If 10.1.0.0/16 and 10.1.5.0/24 both match a destination, the /24 wins because it is more specific. This rule is what makes summaries and more-specific exceptions coexist, and what makes an accidental /32 leak override an entire well-designed hierarchy.',
  },
  {
    id: 'default-route',
    term: 'Default route',
    category: 'Routing',
    short: '0.0.0.0/0 (or ::/0) — the match of last resort.',
    long: 'A prefix length of zero matches every destination, so it is only ever chosen when nothing more specific exists. Access-layer devices usually carry a default route and nothing else.',
  },
  {
    id: 'p2p-link',
    term: 'Point-to-point link',
    category: 'Operations',
    short: 'A two-node segment, addressed with a /30 or, better, a /31.',
    long: 'Router-to-router links need exactly two addresses. A /30 provides them but wastes two more on network and broadcast; a /31 (RFC 3021) provides exactly two and is supported by every current platform. On IPv6, a /127 plays the same role.',
  },
  {
    id: 'magic-number',
    term: 'Magic number',
    aka: 'block size, increment',
    category: 'Subnetting',
    short: '256 minus the interesting octet of the mask — the step between consecutive subnets.',
    long: 'The magic number is a mental shortcut for subnetting without binary. Find the octet where the mask is neither 255 nor 0, subtract it from 256, and that is both the size of each subnet and the increment between their network addresses.',
    example: '/26 → mask 255.255.255.192 → 256 − 192 = 64 → subnets at .0, .64, .128, .192',
  },
  {
    id: 'classful',
    term: 'Classful addressing',
    category: 'IPv4',
    short: 'The obsolete scheme where the first bits of an address fixed its mask.',
    long: 'Before CIDR, an address’s leading bits put it in class A (/8), B (/16), or C (/24), and the mask was implied. It wasted enormous amounts of space — an organization needing 300 addresses got a class B with 65,534. Classes are gone from routing but survive in the vocabulary and in default masks on some CLIs.',
  },
  {
    id: 'dual-stack',
    term: 'Dual stack',
    category: 'IPv6',
    short: 'Running IPv4 and IPv6 simultaneously on the same interfaces.',
    long: 'Dual stack is the standard IPv6 deployment model: every segment has both an IPv4 subnet and an IPv6 prefix, and hosts choose per destination (RFC 6724 / Happy Eyeballs). It means two address plans, two sets of ACLs, and two routing topologies to keep consistent — the main operational cost of the transition.',
  },
  {
    id: 'prefix-delegation',
    term: 'Prefix delegation',
    aka: 'DHCPv6-PD',
    category: 'IPv6',
    short: 'A router requests a whole prefix from upstream rather than a single address.',
    long: 'With DHCPv6-PD an edge router asks its ISP for a block — typically a /56 or /48 — and then subdivides it into /64s for its internal links. It is how home and branch routers get routable IPv6 space without manual assignment.',
  },
  {
    id: 'zero-compression',
    term: 'Zero compression',
    category: 'IPv6',
    short: 'Replacing one run of all-zero hextets with "::", at most once per address.',
    long: 'RFC 5952 sets the canonical rules: drop leading zeros within each hextet, then replace the single longest run of zero hextets with "::". Only one "::" is allowed, because two would make the number of omitted groups ambiguous. Ties are broken in favour of the leftmost run.',
    example: '2001:0db8:0000:0000:0000:0000:0000:0001 → 2001:db8::1',
  },
  {
    id: 'address-plan',
    term: 'Address plan',
    category: 'Operations',
    short: 'The documented allocation scheme that maps address blocks to sites, roles, and environments.',
    long: 'An address plan assigns aggregatable blocks top-down — region, site, function, environment — before any device is configured. Good plans leave deliberate headroom, keep like things adjacent so they summarize, and are recorded in an IPAM system rather than a spreadsheet nobody trusts.',
  },
  {
    id: 'ipam',
    term: 'IPAM',
    aka: 'IP Address Management',
    category: 'Operations',
    short: 'The system of record for which blocks are allocated to what.',
    long: 'IPAM tools (NetBox, Infoblox, phpIPAM, cloud-native equivalents) track allocations, prevent overlap, and feed automation. On any network past a few dozen subnets, the address plan is only as good as the database that records it.',
  },
  {
    id: 'vpc',
    term: 'VPC / VNet',
    category: 'Operations',
    short: 'A cloud provider’s virtual network, defined by a CIDR block you choose at creation.',
    long: 'A VPC (AWS/GCP) or VNet (Azure) is allocated one or more CIDR blocks, which are then divided into per-availability-zone subnets. Cloud providers reserve several addresses in each subnet (AWS reserves five), the block usually cannot shrink after creation, and overlapping CIDRs between VPCs block peering — so subnetting mistakes in cloud are expensive to undo.',
  },
  {
    id: 'availability-zone',
    term: 'Availability zone',
    category: 'Operations',
    short: 'An isolated datacenter within a cloud region; subnets do not span zones.',
    long: 'Because a cloud subnet lives in exactly one availability zone, a highly available service needs one subnet per zone per tier. That multiplies your subnet count by the number of zones and is the single biggest driver of cloud address-plan size.',
  },
  {
    id: 'ospf-area',
    term: 'OSPF area',
    category: 'Routing',
    short: 'A routing domain subdivision; summarization happens at its border.',
    long: 'OSPF areas exist to bound flooding and enable summarization. An area whose addressing is contiguous can be advertised into the backbone as a couple of prefixes; one whose addressing is scattered cannot be summarized at all, and every internal link flap propagates network-wide.',
  },
  {
    id: 'acl',
    term: 'ACL',
    aka: 'Access Control List',
    category: 'Operations',
    short: 'A rule list that permits or denies traffic, usually matched on prefixes.',
    long: 'ACLs and security groups match on address blocks. A hierarchical address plan makes policy short and readable — "deny 10.20.0.0/16 to 10.30.0.0/16" — while a scattered plan forces dozens of individual rules that drift out of date.',
  },
  {
    id: 'mtu',
    term: 'MTU',
    category: 'Foundations',
    short: 'The largest payload a link will carry in one frame, typically 1500 bytes on Ethernet.',
    long: 'MTU is not a subnetting concept, but it interacts with it: IPv6 routers never fragment, so path MTU discovery must work end to end, and tunnels that shrink the effective MTU are a frequent cause of "the network is up but big transfers hang".',
  },
  {
    id: 'loopback-interface',
    term: 'Loopback interface',
    category: 'Operations',
    short: 'A virtual, always-up interface addressed with a /32 (or /128).',
    long: 'Loopbacks give a router a stable identity independent of any physical port — used as the router ID, the source of management sessions, and the BGP peering address. They are allocated from a dedicated block so that all loopbacks in a region summarize into one prefix.',
  },
  {
    id: 'ip-helper',
    term: 'DHCP relay',
    aka: 'ip helper-address',
    category: 'Operations',
    short: 'Forwards a subnet’s DHCP broadcasts to a central server as unicast.',
    long: 'Since DHCP discovery is a broadcast and broadcasts stop at the router, each gateway interface needs a relay pointing at the DHCP servers. The relay stamps the request with the subnet it came from, which is how the server picks the right scope.',
  },
]

export const GLOSSARY_BY_ID: Record<string, GlossaryEntry> = Object.fromEntries(
  GLOSSARY.map((entry) => [entry.id, entry]),
)

export const GLOSSARY_CATEGORIES: GlossaryCategory[] = [
  'Foundations',
  'IPv4',
  'Subnetting',
  'IPv6',
  'Routing',
  'Operations',
]
